version: '3'

services:
  matrix-app:
    build:
      context: .
    working_dir: /var/app
    env_file:
      - .env
    ports:
      - '8080:8080'
    volumes:
      - .:/var/app
    entrypoint: ["sh", "/docker-entrypoint.sh"]
    command: ["npm", "--prefix", "backend/", "run", "start-backend"]
